# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_park_search
#'
#' @noRd
rcpp_park_search <- function (graph, vert_map_in, start_vert) {
    .Call (`_superblock_rcpp_park_search`, graph, vert_map_in, start_vert)
}
