# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' rcpp_park_search
#'
#' @noRd
rcpp_park_search <- function (graph, edge_map_in, edge_map_rev_in, prop_full, start_edge, ntrials) {
    .Call (`_superblock_rcpp_park_search`, graph, edge_map_in, edge_map_rev_in, prop_full, start_edge, ntrials)
}

#' rcpp_park_fill
#'
#' @noRd
rcpp_park_fill <- function (graph, edge_map_in, edge_map_rev_in, prop_full, ntrials, n_unfilled) {
    .Call (`_superblock_rcpp_park_fill`, graph, edge_map_in, edge_map_rev_in, prop_full, ntrials, n_unfilled)
}
